library(googledrive)




drive_mkdir("COMERCIAL/CAMPANHAS/RESULTADOS/2022/NOV2")

gs4_create(name = "RESUMO CAMPANHAS COMERCIAIS NOV22",
           sheets = c("REBATES","INSIGNE","VARILUX","OUTRAS","RETROATIVO"))

drive_mv(file = "RESUMO CAMPANHAS COMERCIAIS NOV22", path = "COMERCIAL/CAMPANHAS/RESULTADOS/2022/NOV") 