WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON 
       C.CLICODIGO=A.CLICODIGO WHERE C.CLICODIGO IN ({CLIENTES_TGEN8_MAI23$CLICODIGO*}) ),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,SETOR,CLINOMEFANT,PEDAUTORIZOU  
FROM PEDID 
INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
WHERE PEDDTBAIXA
BETWEEN '01.05.2023'
       AND '30.06.2023'
AND PEDSITPED <>'C'),

-- 1  Varilux Series Transitions 100 pontos

PROD1 AS (SELECT PROCODIGO,
        PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND 
         ((PRODESCRICAO LIKE '%VARILUX 4D%' AND 
           PRODESCRICAO LIKE '%TGEN8%') OR
         (PRODESCRICAO LIKE '%VARILUX X%' AND 
           PRODESCRICAO LIKE '%TGEN8%') OR 
           (PRODESCRICAO LIKE '%VARILUX E%' AND 
             PRODESCRICAO LIKE '%TGEN8%'))),

-- 2  Varilux Digital Transitions 70 pontos

PROD2 AS (SELECT PROCODIGO,
        PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND 
         ((PRODESCRICAO LIKE '%COMFORT MAX%' AND
            PRODESCRICAO LIKE '%TGEN8%') OR 
             (PRODESCRICAO LIKE '%LIBERTY%' AND 
               PRODESCRICAO LIKE '%TGEN8%') OR 
               (PRODESCRICAO LIKE '%PHYSIO%' AND 
                 PRODESCRICAO LIKE '%TGEN8%')) AND
                  GR1CODIGO=15 AND PROSITUACAO='A'AND 
                   PROCODIGO2 IS NULL),
                   
-- 3  Varilux tradicional Transitions 60 pontos

PROD3 AS (SELECT PROCODIGO,
        PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND 
         ((PRODESCRICAO LIKE '%COMFORT%' AND 
           PRODESCRICAO LIKE '%TGEN8%') OR 
           (PRODESCRICAO LIKE '%LIBERTY%' AND 
             PRODESCRICAO LIKE '%TGEN8%') OR 
               (PRODESCRICAO LIKE '%PHYSIO%' AND 
                 PRODESCRICAO LIKE '%TGEN8%')) AND
                  LEFT(PROCODIGO,2)='LP' AND 
                   PROSITUACAO='A'AND 
                    PROCODIGO2 IS NULL),
                  

-- 4 Progressivo Kodak transitions 50 pontos

PROD4 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE MARCODIGO=24 AND 
         PRODESCRICAO LIKE '%TGEN8%' AND 
          LEFT(PROCODIGO,2) IN ('LD','LP') AND 
            PROSITUACAO='A'AND
             GR2CODIGO=1 AND
             PROCODIGO2 IS NULL),
             
-- 5 lente visão simples transitions Eyezen e Kodak single 50  pontos             

PROD5 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE  
((PRODESCRICAO LIKE '%KODAK SINGLE%' AND 
  PRODESCRICAO LIKE '%TGEN8%') OR
(PRODESCRICAO LIKE '%EYEZEN%' AND 
  PRODESCRICAO LIKE '%TGEN8%')) AND
PROSITUACAO='A'AND 
PROCODIGO2 IS NULL AND GR1CODIGO<>17),

-- 6 lente pronta crizal transitions 35 pontos

PROD6 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE  
             (PRODESCRICAO LIKE '%TGEN8%' AND 
               PRODESCRICAO LIKE '%CRIZAL%') AND 
                GR2CODIGO=3 AND 
                 PROSITUACAO='A'AND 
                   PROCODIGO2=IIF(PROCODIGO2 IS NULL,PROCODIGO,PROCODIGO2)),

-- 7 lente pronta kodak no reflex transitions 25 pontos

PROD7 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE  
             (PRODESCRICAO LIKE '%TGEN8%' AND 
               PRODESCRICAO LIKE '%NO REFLEX%') AND 
                GR2CODIGO=3 AND PROSITUACAO='A'AND 
                  PROCODIGO2=IIF(PROCODIGO2 IS NULL,PROCODIGO,PROCODIGO2)),


PED_PROMO_PAP AS (SELECT P.ID_PEDIDO ID_PEDIDO_PROMO FROM PDPRD P
 INNER JOIN PD ON P.ID_PEDIDO=PD.ID_PEDIDO
   WHERE PROCODIGO='PAP'),
   
   
PED_PROMO_PLUGIN AS (SELECT ID_PEDIDPROMOCAO ID_PEDIDO_PROMO FROM PEDIDPROMO P
   INNER JOIN PD ON P.ID_PEDIDPROMOCAO=PD.ID_PEDIDO),

PED_PROMO_UNION AS (SELECT ID_PEDIDO_PROMO FROM PED_PROMO_PAP UNION
SELECT ID_PEDIDO_PROMO FROM PED_PROMO_PLUGIN)

--- PROD1

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD1.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(100 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD1 ON PDPRD.PROCODIGO=PROD1.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD2

SELECT
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD2.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(70 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD2 ON PDPRD.PROCODIGO=PROD2.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD3

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PROD3.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(60 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD3 ON PDPRD.PROCODIGO=PROD3.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD4

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD4.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(50 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD4 ON PDPRD.PROCODIGO=PROD4.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD5

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD5.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(50 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD5 ON PDPRD.PROCODIGO=PROD5.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD6

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD6.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(35 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD6 ON PDPRD.PROCODIGO=PROD6.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD7

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD7.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(25 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD7 ON PDPRD.PROCODIGO=PROD7.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2


FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD8 ON PDPRD.PROCODIGO=PROD8.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2