-- SQL MODELOS DE CAMPANHAS
-- ULTIMA ATUALIZAÇÃO 13.06.2024

-- CTE CAMPANHAS
WITH CAMPANHAS AS (
    SELECT C.CLICODIGO, GCLCODIGO,P.ID_PROMO, DESCRICAO AS CAMPANHA
    FROM CLIPROMO C
    LEFT JOIN PROMO P ON C.ID_PROMO = P.ID_PROMO
    LEFT JOIN CLIEN CL ON C.CLICODIGO=CL.CLICODIGO
    WHERE DESCRICAO LIKE '%ALELO REBATES%')
                  
SELECT C.CLICODIGO,GCLCODIGO
FROM CAMPANHAS C

