WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON 
       C.CLICODIGO=A.CLICODIGO WHERE C.CLICODIGO IN (1744,4825)),

PED AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,SETOR,CLINOMEFANT,PEDAUTORIZOU  
FROM PEDID 
INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
WHERE 
PEDDTBAIXA
       BETWEEN '01.01.2024'
       AND '31.01.2024'
AND PEDSITPED <>'C'),

PROD AS (SELECT PROCODIGO FROM PRODU WHERE PROSITUACAO='A'),

-- UZ+

PROD1 AS (SELECT PROCODIGO,PRODESCRICAO, 10 BONUS FROM PRODU WHERE  
                  ((PRODESCRICAO LIKE '%UZ+%' AND 
                  PRODESCRICAO LIKE '%1.50%')) AND 
                  (PRODESCRICAO NOT LIKE '%TGEN8%') AND
                  (PRODESCRICAO NOT LIKE '%TRANS%') AND
                  (PRODESCRICAO NOT LIKE '%FOTO%') AND
                  GR2CODIGO=1 AND 
                  PROSITUACAO='A'AND 
                  PROCODIGO2 IS NULL),

PROD2 AS (SELECT PROCODIGO,PRODESCRICAO, 40 BONUS FROM PRODU WHERE  
                  ((PRODESCRICAO LIKE '%UZ+%' AND 
                  PRODESCRICAO LIKE '%1.50%')) AND 
                  (PRODESCRICAO LIKE '%TGEN8%' OR PRODESCRICAO LIKE '%TRANS%' OR PRODESCRICAO LIKE '%FOTO%') AND
                  GR2CODIGO=1 AND 
                  PROSITUACAO='A'AND 
                  PROCODIGO2 IS NULL),
                 
                  
PROD3 AS (SELECT PROCODIGO,PRODESCRICAO, 20 BONUS FROM PRODU WHERE  
                  ((PRODESCRICAO LIKE '%UZ+%' AND 
                  PRODESCRICAO LIKE '%1.67%')) AND 
                  (PRODESCRICAO NOT LIKE '%TGEN8%') AND
                  (PRODESCRICAO NOT LIKE '%TRANS%') AND
                  (PRODESCRICAO NOT LIKE '%FOTO%') AND
                  GR2CODIGO=1 AND 
                  PROSITUACAO='A'AND 
                  PROCODIGO2 IS NULL),                  

-- ACTUALITE

PROD4 AS (SELECT PROCODIGO,PRODESCRICAO, 20 BONUS FROM PRODU WHERE  
                  ((PRODESCRICAO LIKE '%ACTUALITE%' AND 
                  PRODESCRICAO LIKE '%1.50%')) AND 
                  (PRODESCRICAO NOT LIKE '%TGEN8%') AND
                  (PRODESCRICAO NOT LIKE '%TRANS%') AND
                  (PRODESCRICAO NOT LIKE '%FOTO%') AND
                  GR2CODIGO=1 AND 
                  PROSITUACAO='A'AND 
                  PROCODIGO2 IS NULL),
                  

PROD5 AS (SELECT PROCODIGO,PRODESCRICAO, 60 BONUS FROM PRODU WHERE  
                  ((PRODESCRICAO LIKE '%ACTUALITE%' AND 
                  PRODESCRICAO LIKE '%1.50%')) AND 
                  (PRODESCRICAO LIKE '%TGEN8%' OR PRODESCRICAO LIKE '%TRANS%' OR PRODESCRICAO LIKE '%FOTO%') AND
                  GR2CODIGO=1 AND 
                  PROSITUACAO='A'AND 
                  PROCODIGO2 IS NULL),
                  

                  
PROD6 AS (SELECT PROCODIGO,PRODESCRICAO, 30 BONUS FROM PRODU WHERE  
                  ((PRODESCRICAO LIKE '%ACTUALITE%' AND 
                  PRODESCRICAO LIKE '%1.67%')) AND
                  GR2CODIGO=1 AND 
                  PROSITUACAO='A'AND 
                  PROCODIGO2 IS NULL),                  
                  
-- AVANCE

PROD7 AS (SELECT PROCODIGO,PRODESCRICAO, 30 BONUS FROM PRODU WHERE  
                  ((PRODESCRICAO LIKE '%AVANCE%' AND 
                  PRODESCRICAO LIKE '%1.50%')) AND 
                  (PRODESCRICAO NOT LIKE '%TGEN8%') AND
                  (PRODESCRICAO NOT LIKE '%TRANS%') AND
                  (PRODESCRICAO NOT LIKE '%FOTO%') AND
                  GR2CODIGO=1 AND 
                  PROSITUACAO='A'AND 
                  PROCODIGO2 IS NULL),
                 

PROD8 AS (SELECT PROCODIGO,PRODESCRICAO, 80 BONUS FROM PRODU WHERE  
                  ((PRODESCRICAO LIKE '%AVANCE%' AND 
                  PRODESCRICAO LIKE '%1.50%')) AND 
                  (PRODESCRICAO LIKE '%TGEN8%' OR PRODESCRICAO LIKE '%TRANS%' OR PRODESCRICAO LIKE '%FOTO%') AND
                  GR2CODIGO=1 AND 
                  PROSITUACAO='A'AND 
                  PROCODIGO2 IS NULL),                 
                 

PROD9 AS (SELECT PROCODIGO,PRODESCRICAO, 40 BONUS FROM PRODU WHERE  
                  ((PRODESCRICAO LIKE '%AVANCE%' AND 
                  PRODESCRICAO LIKE '%1.67%')) AND
                  GR2CODIGO=1 AND 
                  PROSITUACAO='A'AND 
                  PROCODIGO2 IS NULL),
                 
RESULT AS (                 
SELECT 
PD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      CASE 
      WHEN  PROD1.PROCODIGO IS NOT NULL THEN PROD1.BONUS
      WHEN  PROD2.PROCODIGO IS NOT NULL THEN PROD2.BONUS
      WHEN  PROD3.PROCODIGO IS NOT NULL THEN PROD3.BONUS
      WHEN  PROD4.PROCODIGO IS NOT NULL THEN PROD4.BONUS
      WHEN  PROD5.PROCODIGO IS NOT NULL THEN PROD5.BONUS
      WHEN  PROD6.PROCODIGO IS NOT NULL THEN PROD6.BONUS
      WHEN  PROD7.PROCODIGO IS NOT NULL THEN PROD7.BONUS
      WHEN  PROD8.PROCODIGO IS NOT NULL THEN PROD8.BONUS
      WHEN  PROD9.PROCODIGO IS NOT NULL THEN PROD9.BONUS


      ELSE 0 END BONUS, 
       
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA
FROM
PDPRD PD
INNER JOIN PED p ON PD.ID_PEDIDO=P.ID_PEDIDO
INNER JOIN FIS F ON PD.FISCODIGO=F.FISCODIGO
INNER JOIN PROD  ON PD.PROCODIGO=PROD.PROCODIGO
LEFT JOIN PROD1 ON PD.PROCODIGO=PROD1.PROCODIGO
LEFT JOIN PROD2 ON PD.PROCODIGO=PROD2.PROCODIGO
LEFT JOIN PROD3 ON PD.PROCODIGO=PROD3.PROCODIGO
LEFT JOIN PROD4 ON PD.PROCODIGO=PROD4.PROCODIGO
LEFT JOIN PROD5 ON PD.PROCODIGO=PROD5.PROCODIGO
LEFT JOIN PROD6 ON PD.PROCODIGO=PROD6.PROCODIGO
LEFT JOIN PROD7 ON PD.PROCODIGO=PROD7.PROCODIGO
LEFT JOIN PROD8 ON PD.PROCODIGO=PROD8.PROCODIGO
LEFT JOIN PROD9 ON PD.PROCODIGO=PROD9.PROCODIGO


GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2)

SELECT * FROM RESULT WHERE BONUS<>0



