## CAMPANHA TRANSITIONS

library(DBI)
library(tidyverse)
library(lubridate)
library(googlesheets4)

## ============================================================================================

con2 <- dbConnect(odbc::odbc(), "reproreplica")

## =============================================================================================================         

# SQL TRANSITIONS

CP_TRANSITIONS_0922 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON 
       C.CLICODIGO=A.CLICODIGO WHERE C.CLICODIGO IN (1426,3996,1863,168,4183,290,1290,4429,1407,1408,2203,871,2184,3953,4081,4514,4301,1458,154,477,1329,1232,1818,1771,463,685,173,672,145,291,2154,1761,397,771,4175,151,1701,792,4414,3963,198,713,674,214,2060,4146,1336,3810,1745,4001,4077,845,317,3817,2245,1669,1729,1349,3821,1241,2276,1135,4117,1184,3783,1464,669,4166,395,314,544,1940,1983,1886,510,1784,4492,4498,2246,2241,2242,2243,843,320,2064,745,278,450,881,1836)),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,SETOR,CLINOMEFANT,PEDAUTORIZOU  
FROM PEDID 
INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
WHERE PEDDTBAIXA
BETWEEN '01.08.2022'
       AND 'TODAY'
AND PEDSITPED <>'C'),

PROD1 AS (SELECT PROCODIGO,
        PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND 
         (PRODESCRICAO LIKE '%VARILUX X%' AND 
           PRODESCRICAO LIKE '%TGEN8%') OR 
           (PRODESCRICAO LIKE '%VARILUX E%' AND 
             PRODESCRICAO LIKE '%TGEN8%') ),

PROD2 AS (SELECT PROCODIGO,
        PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND 
         ((PRODESCRICAO LIKE '%COMFORT MAX%' AND
            PRODESCRICAO LIKE '%TGEN8%') OR 
             (PRODESCRICAO LIKE '%LIBERTY%' AND 
               PRODESCRICAO LIKE '%TGEN8%') OR 
               (PRODESCRICAO LIKE '%PHYSIO%' AND 
                 PRODESCRICAO LIKE '%TGEN8%')) AND
                  GR1CODIGO=15 AND PROSITUACAO='A'AND 
                   PROCODIGO2 IS NULL),

PROD3 AS (SELECT PROCODIGO,
        PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND 
         ((PRODESCRICAO LIKE '%COMFORT%' AND 
           PRODESCRICAO LIKE '%TGEN8%') OR 
           (PRODESCRICAO LIKE '%LIBERTY%' AND 
             PRODESCRICAO LIKE '%TGEN8%') OR 
               (PRODESCRICAO LIKE '%PHYSIO%' AND 
                 PRODESCRICAO LIKE '%TGEN8%')) AND
                  LEFT(PROCODIGO,2)='LP' AND 
                   PROSITUACAO='A'AND 
                    PROCODIGO2 IS NULL),

PROD4 AS (SELECT PROCODIGO,
        PRODESCRICAO FROM PRODU WHERE MARCODIGO=24 AND 
         PRODESCRICAO LIKE '%TGEN8%' AND 
          LEFT(PROCODIGO,2) IN ('LD','LP') AND 
            PROSITUACAO='A'AND 
             PROCODIGO2 IS NULL),

PROD5 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE  
             (PRODESCRICAO LIKE '%TGEN8%') AND 
               (PRODESCRICAO LIKE '%EYEZEN%' OR 
                PRODESCRICAO LIKE '%KODAK SINGLE%')AND
                 (PRODESCRICAO NOT LIKE '%SCL%') AND 
                   GR2CODIGO=3 AND GR1CODIGO<>1 AND 
                    PROSITUACAO='A'AND 
                     PROCODIGO2 IS NULL),

PROD6 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE  
             (PRODESCRICAO LIKE '%TGEN8%' AND 
               PRODESCRICAO LIKE '%CRIZAL%') AND 
                GR2CODIGO=3 AND 
                 PROSITUACAO='A'AND 
                  PROCODIGO2 IS NULL AND
                   PROCODIGO2=IIF(PROCODIGO2 IS NULL,PROCODIGO,PROCODIGO2)),

PROD7 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE  
             (PRODESCRICAO LIKE '%TGEN8%' AND 
               PRODESCRICAO LIKE '%NO REFLEX%') AND 
                GR2CODIGO=3 AND PROSITUACAO='A'AND 
                  PROCODIGO2=IIF(PROCODIGO2 IS NULL,PROCODIGO,PROCODIGO2)),

PROD8 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE  
             (PRODESCRICAO LIKE '%TGEN8%') AND 
               (PRODESCRICAO LIKE '%EYEZEN%' OR 
                PRODESCRICAO LIKE '%KODAK SINGLE%')AND
                 (PRODESCRICAO LIKE '%SCL%') AND 
                   GR2CODIGO=3 AND 
                    GR1CODIGO<>1 AND 
                     PROSITUACAO='A'AND 
                      PROCODIGO2 IS NULL),

PED_PROMO_PAP AS (SELECT P.ID_PEDIDO ID_PEDIDO_PROMO FROM PDPRD P
 INNER JOIN PD ON P.ID_PEDIDO=PD.ID_PEDIDO
   WHERE PROCODIGO='PAP'),
   
   
PED_PROMO_PLUGIN AS (SELECT ID_PEDIDPROMOCAO ID_PEDIDO_PROMO FROM PEDIDPROMO P
   INNER JOIN PD ON P.ID_PEDIDPROMOCAO=PD.ID_PEDIDO),

PED_PROMO_UNION AS (SELECT ID_PEDIDO_PROMO FROM PED_PROMO_PAP UNION
SELECT ID_PEDIDO_PROMO FROM PED_PROMO_PLUGIN)

--- PROD1

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD1.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(100 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD1 ON PDPRD.PROCODIGO=PROD1.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD2

SELECT
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD2.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(70 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD2 ON PDPRD.PROCODIGO=PROD2.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD3

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PROD3.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(60 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD3 ON PDPRD.PROCODIGO=PROD3.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD4

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD4.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(50 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD4 ON PDPRD.PROCODIGO=PROD4.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD5

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD5.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(50 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD5 ON PDPRD.PROCODIGO=PROD5.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD6

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD6.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(35 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD6 ON PDPRD.PROCODIGO=PROD6.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD6

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD6.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(25 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD6 ON PDPRD.PROCODIGO=PROD6.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD7

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD6.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(120 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD6 ON PDPRD.PROCODIGO=PROD6.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD8

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD6.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(75 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD6 ON PDPRD.PROCODIGO=PROD6.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2


 ") %>%
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) %>% 
  mutate(CPF=sub("\\.", '',CPF)) %>% 
  mutate(CPF=sub("\\-", '',CPF)) %>% 
  mutate(CPF=sub("\\,", '',CPF)) 

View(CP_TRANSITIONS_0922)

CP_TRANSITIONS_0922 %>% summarize(v=sum(VRVENDA))

CP_TRANSITIONS_0922 %>% summarize(v=sum(BONUS))

OBS_CP_TRANSITIONS_0922 <- paste0("TRANSITIONS ",CP_TRANSITIONS_0922,
                     " ",format(floor_date(Sys.Date()-months(1),"month"),"%m/%y")) 


## JOIN CPF

LIST_CP_TRANSITIONS_0922   <- inner_join(CP_CP_TRANSITIONS_0922 ,BASE_CPF,by="CLICODIGO") %>% 
  rename(CPF1=CPF.x) %>% rename(CPF2=CPF.y) %>% 
  .[,-12] %>% 
  rename(.,"CPF"="CPF2") %>% 
  mutate(OBS=OBS_CP_TRANSITIONS_0922 )

View(LIST_CP_TRANSITIONS_0922 )


### PAY

PAG_CP_TRANSITIONS_0922 <- LIST_CP_TRANSITIONS_0922  %>% group_by(CPF) %>% 
  summarize(BONUS=round(sum(BONUS),2)) %>% 
  mutate(OBS=OBS_CP_TRANSITIONS_0922 ) 

View(PAG_4253_0622)


PAG_4253_0622 %>% summarize(v=sum(BONUS))


