## CAMPANHA TRANSITIONS PONTOS ESSILOR T1 2023

library(DBI)
library(tidyverse)
library(lubridate)
library(googlesheets4)
library(glue)

## ============================================================================================

con2 <- dbConnect(odbc::odbc(), "reproreplica")

## =============================================================================================================         
### CLIENTES TRANSITIONS


CLIENTES_TGEN8_FEV_23 <- read_sheet(ss="12PrOZ-jf2dV0Ydz2gEmo3dncAto0t3u5nNnpRu5JEcU",sheet = "CLIENTES") %>% 
                              filter(INICIO==as.Date('2023-02-01'))


CLIENTES_TGEN8_MAR_23 <- read_sheet(ss="12PrOZ-jf2dV0Ydz2gEmo3dncAto0t3u5nNnpRu5JEcU",sheet = "CLIENTES") %>% 
  filter(INICIO==as.Date('2023-03-01'))




cli <- dbGetQuery(con2,"SELECT DISTINCT C.CLICODIGO,
                          CLINOMEFANT,
                           C.GCLCODIGO,
                                    SETOR
                                     FROM CLIEN C
                                      LEFT JOIN (SELECT CLICODIGO,E.ZOCODIGO,CIDNOME,ZODESCRICAO SETOR,ENDCODIGO FROM ENDCLI E
                                       LEFT JOIN CIDADE CID ON E.CIDCODIGO=CID.CIDCODIGO
                                        LEFT JOIN (SELECT ZOCODIGO,ZODESCRICAO FROM ZONA WHERE ZOCODIGO IN (20,21,22,23,24,25,26,27,28))Z ON E.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
                                         LEFT JOIN GRUPOCLI GR ON C.GCLCODIGO=GR.GCLCODIGO
                                          WHERE CLICLIENTE='S'")


## CLIENTES FEVEREIRO

CP_CLIENTES_TGEN8_FEV_23_sql <- glue_sql("
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON 
       C.CLICODIGO=A.CLICODIGO WHERE C.CLICODIGO IN ({CLIENTES_TGEN8_FEV_23$CLICODIGO*}) ),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,SETOR,CLINOMEFANT,PEDAUTORIZOU  
FROM PEDID 
INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
WHERE PEDDTBAIXA
BETWEEN '01.02.2023'
       AND '31.03.2023'
AND PEDSITPED <>'C'),

-- Varilux Series Transitions 100 pontos

PROD1 AS (SELECT PROCODIGO,
        PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND 
         (PRODESCRICAO LIKE '%VARILUX X%' AND 
           PRODESCRICAO LIKE '%TGEN8%') OR 
           (PRODESCRICAO LIKE '%VARILUX E%' AND 
             PRODESCRICAO LIKE '%TGEN8%') ),

-- Varilux Digital Transitions 70 pontos

PROD2 AS (SELECT PROCODIGO,
        PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND 
         ((PRODESCRICAO LIKE '%COMFORT MAX%' AND
            PRODESCRICAO LIKE '%TGEN8%') OR 
             (PRODESCRICAO LIKE '%LIBERTY%' AND 
               PRODESCRICAO LIKE '%TGEN8%') OR 
               (PRODESCRICAO LIKE '%PHYSIO%' AND 
                 PRODESCRICAO LIKE '%TGEN8%')) AND
                  GR1CODIGO=15 AND PROSITUACAO='A'AND 
                   PROCODIGO2 IS NULL),
                   
-- Varilux tradicional Transitions 60 pontos

PROD3 AS (SELECT PROCODIGO,
        PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND 
         ((PRODESCRICAO LIKE '%COMFORT%' AND 
           PRODESCRICAO LIKE '%TGEN8%') OR 
           (PRODESCRICAO LIKE '%LIBERTY%' AND 
             PRODESCRICAO LIKE '%TGEN8%') OR 
               (PRODESCRICAO LIKE '%PHYSIO%' AND 
                 PRODESCRICAO LIKE '%TGEN8%')) AND
                  LEFT(PROCODIGO,2)='LP' AND 
                   PROSITUACAO='A'AND 
                    PROCODIGO2 IS NULL),
                    
 -- Eyezen transitions 55 pontos

PROD4 AS (SELECT PROCODIGO,
        PRODESCRICAO FROM PRODU WHERE
         (PRODESCRICAO LIKE '%EYEZEN%' AND PRODESCRICAO LIKE '%TGEN8%') AND
           LEFT(PROCODIGO,2)='LD' AND
            PROSITUACAO='A'),

-- Progressivo Kodak transitions 50 pontos

PROD5 AS (SELECT PROCODIGO,
        PRODESCRICAO FROM PRODU WHERE MARCODIGO=24 AND 
         PRODESCRICAO LIKE '%TGEN8%' AND 
          LEFT(PROCODIGO,2) IN ('LD','LP') AND 
            PROSITUACAO='A'AND 
             PROCODIGO2 IS NULL),
             
-- lente visão simples transitions kodak single eyezen 45 pontos             

PROD6 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE  
                (PRODESCRICAO LIKE '%KODAK SINGLE%' AND 
         PRODESCRICAO LIKE '%TGEN8%') AND
                    PROSITUACAO='A'AND 
                     PROCODIGO2 IS NULL),

-- lente pronta crizal transitions 35 pontos

PROD7 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE  
             (PRODESCRICAO LIKE '%TGEN8%' AND 
               PRODESCRICAO LIKE '%CRIZAL%') AND 
                GR2CODIGO=3 AND 
                 PROSITUACAO='A'AND 
                   PROCODIGO2=IIF(PROCODIGO2 IS NULL,PROCODIGO,PROCODIGO2)),

-- lente pronta kodak no reflex transitions 25 pontos

PROD8 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE  
             (PRODESCRICAO LIKE '%TGEN8%' AND 
               PRODESCRICAO LIKE '%NO REFLEX%') AND 
                GR2CODIGO=3 AND PROSITUACAO='A'AND 
                  PROCODIGO2=IIF(PROCODIGO2 IS NULL,PROCODIGO,PROCODIGO2)),


PED_PROMO_PAP AS (SELECT P.ID_PEDIDO ID_PEDIDO_PROMO FROM PDPRD P
 INNER JOIN PD ON P.ID_PEDIDO=PD.ID_PEDIDO
   WHERE PROCODIGO='PAP'),
   
   
PED_PROMO_PLUGIN AS (SELECT ID_PEDIDPROMOCAO ID_PEDIDO_PROMO FROM PEDIDPROMO P
   INNER JOIN PD ON P.ID_PEDIDPROMOCAO=PD.ID_PEDIDO),

PED_PROMO_UNION AS (SELECT ID_PEDIDO_PROMO FROM PED_PROMO_PAP UNION
SELECT ID_PEDIDO_PROMO FROM PED_PROMO_PLUGIN)

--- PROD1

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD1.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(100 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD1 ON PDPRD.PROCODIGO=PROD1.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD2

SELECT
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD2.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(70 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD2 ON PDPRD.PROCODIGO=PROD2.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD3

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PROD3.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(60 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD3 ON PDPRD.PROCODIGO=PROD3.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD4

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD4.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(55 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD4 ON PDPRD.PROCODIGO=PROD4.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD5

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD5.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(50 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD5 ON PDPRD.PROCODIGO=PROD5.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD6

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD6.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(45 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD6 ON PDPRD.PROCODIGO=PROD6.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD7

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD7.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(35 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD7 ON PDPRD.PROCODIGO=PROD7.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD8

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD8.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(25 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD8 ON PDPRD.PROCODIGO=PROD8.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2


 ")

CP_TRANSITIONS_FEV_23<-  dbGetQuery(con2,CP_CLIENTES_TGEN8_FEV_23_sql) 

View(CP_TRANSITIONS_FEV_23)

CP_TRANSITIONS_FEV_23 %>% summarize(v=sum(VRVENDA))

CP_TRANSITIONS_FEV_23 %>% summarize(v=sum(BONUS))


## RESULTADO GERAL

RESULT_TRANSITIONS_FEV_23 <- CP_TRANSITIONS_FEV_23 %>% 
  group_by(CLICODIGO) %>% 
  summarize(BONUS=sum(BONUS)) %>% 
  as.data.frame() %>% 
  left_join(.,cli,by="CLICODIGO") %>% 
   arrange(desc(BONUS))

View(RESULT_TRANSITIONS_FEV_23)


## CLIENTES MAR 23

CP_CLIENTES_TGEN8_MAR_23_sql <- glue_sql("
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON 
       C.CLICODIGO=A.CLICODIGO WHERE C.CLICODIGO IN ({CLIENTES_TGEN8_MAR_23$CLICODIGO*}) ),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,SETOR,CLINOMEFANT,PEDAUTORIZOU  
FROM PEDID 
INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
WHERE PEDDTBAIXA
BETWEEN '01.03.2023'
       AND '31.03.2023'
AND PEDSITPED <>'C'),

-- Varilux Series Transitions 100 pontos

PROD1 AS (SELECT PROCODIGO,
        PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND 
         (PRODESCRICAO LIKE '%VARILUX X%' AND 
           PRODESCRICAO LIKE '%TGEN8%') OR 
           (PRODESCRICAO LIKE '%VARILUX E%' AND 
             PRODESCRICAO LIKE '%TGEN8%') ),

-- Varilux Digital Transitions 70 pontos

PROD2 AS (SELECT PROCODIGO,
        PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND 
         ((PRODESCRICAO LIKE '%COMFORT MAX%' AND
            PRODESCRICAO LIKE '%TGEN8%') OR 
             (PRODESCRICAO LIKE '%LIBERTY%' AND 
               PRODESCRICAO LIKE '%TGEN8%') OR 
               (PRODESCRICAO LIKE '%PHYSIO%' AND 
                 PRODESCRICAO LIKE '%TGEN8%')) AND
                  GR1CODIGO=15 AND PROSITUACAO='A'AND 
                   PROCODIGO2 IS NULL),
                   
-- Varilux tradicional Transitions 60 pontos

PROD3 AS (SELECT PROCODIGO,
        PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND 
         ((PRODESCRICAO LIKE '%COMFORT%' AND 
           PRODESCRICAO LIKE '%TGEN8%') OR 
           (PRODESCRICAO LIKE '%LIBERTY%' AND 
             PRODESCRICAO LIKE '%TGEN8%') OR 
               (PRODESCRICAO LIKE '%PHYSIO%' AND 
                 PRODESCRICAO LIKE '%TGEN8%')) AND
                  LEFT(PROCODIGO,2)='LP' AND 
                   PROSITUACAO='A'AND 
                    PROCODIGO2 IS NULL),
                    
 -- Eyezen transitions 55 pontos

PROD4 AS (SELECT PROCODIGO,
        PRODESCRICAO FROM PRODU WHERE
         (PRODESCRICAO LIKE '%EYEZEN%' AND PRODESCRICAO LIKE '%TGEN8%') AND
           LEFT(PROCODIGO,2)='LD' AND
            PROSITUACAO='A'),

-- Progressivo Kodak transitions 50 pontos

PROD5 AS (SELECT PROCODIGO,
        PRODESCRICAO FROM PRODU WHERE MARCODIGO=24 AND 
         PRODESCRICAO LIKE '%TGEN8%' AND 
          LEFT(PROCODIGO,2) IN ('LD','LP') AND 
            PROSITUACAO='A'AND 
             PROCODIGO2 IS NULL),
             
-- lente visão simples transitions kodak single eyezen 45 pontos             

PROD6 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE  
                (PRODESCRICAO LIKE '%KODAK SINGLE%' AND 
         PRODESCRICAO LIKE '%TGEN8%') AND
                    PROSITUACAO='A'AND 
                     PROCODIGO2 IS NULL),

-- lente pronta crizal transitions 35 pontos

PROD7 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE  
             (PRODESCRICAO LIKE '%TGEN8%' AND 
               PRODESCRICAO LIKE '%CRIZAL%') AND 
                GR2CODIGO=3 AND 
                 PROSITUACAO='A'AND 
                   PROCODIGO2=IIF(PROCODIGO2 IS NULL,PROCODIGO,PROCODIGO2)),

-- lente pronta kodak no reflex transitions 25 pontos

PROD8 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE  
             (PRODESCRICAO LIKE '%TGEN8%' AND 
               PRODESCRICAO LIKE '%NO REFLEX%') AND 
                GR2CODIGO=3 AND PROSITUACAO='A'AND 
                  PROCODIGO2=IIF(PROCODIGO2 IS NULL,PROCODIGO,PROCODIGO2)),


PED_PROMO_PAP AS (SELECT P.ID_PEDIDO ID_PEDIDO_PROMO FROM PDPRD P
 INNER JOIN PD ON P.ID_PEDIDO=PD.ID_PEDIDO
   WHERE PROCODIGO='PAP'),
   
   
PED_PROMO_PLUGIN AS (SELECT ID_PEDIDPROMOCAO ID_PEDIDO_PROMO FROM PEDIDPROMO P
   INNER JOIN PD ON P.ID_PEDIDPROMOCAO=PD.ID_PEDIDO),

PED_PROMO_UNION AS (SELECT ID_PEDIDO_PROMO FROM PED_PROMO_PAP UNION
SELECT ID_PEDIDO_PROMO FROM PED_PROMO_PLUGIN)

--- PROD1

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD1.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(100 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD1 ON PDPRD.PROCODIGO=PROD1.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD2

SELECT
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD2.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(70 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD2 ON PDPRD.PROCODIGO=PROD2.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD3

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PROD3.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(60 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD3 ON PDPRD.PROCODIGO=PROD3.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD4

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PROD4.PROCODIGO,
       PDPDESCRICAO,
        PEDAUTORIZOU,
         SUM(PDPQTDADE)QTD,
          SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(55 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD4 ON PDPRD.PROCODIGO=PROD4.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD5

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD5.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(50 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD5 ON PDPRD.PROCODIGO=PROD5.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD6

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD6.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(45 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD6 ON PDPRD.PROCODIGO=PROD6.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD7

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD7.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(35 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD7 ON PDPRD.PROCODIGO=PROD7.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD8

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD8.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(25 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD8 ON PDPRD.PROCODIGO=PROD8.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2


 ")

CP_TRANSITIONS_MAR_23 <-  dbGetQuery(con2,CP_CLIENTES_TGEN8_MAR_23_sql) 

View(CP_TRANSITIONS_MAR_23)

CP_TRANSITIONS_MAR_23 %>% summarize(v=sum(VRVENDA))

CP_TRANSITIONS_MAR_23 %>% summarize(v=sum(BONUS))



OBS_CP_TRANSITIONS_FEV_MAR_23 <- paste0("TRANSITIONS PONTOS ESSILOR FEV MAR 23") 


## PEDIDOS

LIST_CP_TRANSITIONS_FEV_MAR_23   <- rbind(CP_TRANSITIONS_FEV_23,CP_TRANSITIONS_MAR_23) %>% 
                                     mutate(OBS=OBS_CP_TRANSITIONS_FEV_MAR_23)

View(LIST_CP_TRANSITIONS_FEV_MAR_23)


range_write(LIST_CP_TRANSITIONS_FEV_MAR_23,ss="1ZQRRjkno1vFg2a2QIc6oy4w_Z7KcOZZEQXhyOw31GKg",range = "A1",sheet = "PEDIDOS")



## RESULTADO GERAL

RESULT_TRANSITIONS_FEV_MAR_23 <- LIST_CP_TRANSITIONS_FEV_MAR_23 %>% 
                                  group_by(CLICODIGO) %>% 
                                   summarize(BONUS=sum(BONUS)) %>% 
                                    as.data.frame() %>% 
                                     left_join(.,cli,by="CLICODIGO") %>% 
                                      arrange(desc(BONUS))
                                  

View(RESULT_TRANSITIONS_FEV_MAR_23)


RESULT_TRANSITIONS_FEV_MAR_23_LOJAS <- RESULT_TRANSITIONS_FEV_MAR_23 %>%  filter(is.na(GCLCODIGO))

RESULT_TRANSITIONS_FEV_MAR_23_GRUPOS <- RESULT_TRANSITIONS_FEV_MAR_23 %>%  filter(!is.na(GCLCODIGO)) %>% arrange(GCLCODIGO)


range_write(RESULT_TRANSITIONS_FEV_MAR_23_LOJAS,ss="1ZQRRjkno1vFg2a2QIc6oy4w_Z7KcOZZEQXhyOw31GKg",range = "A1",sheet = "RESULTADO GERAL LOJAS")

range_write(RESULT_TRANSITIONS_FEV_MAR_23_GRUPOS,ss="1ZQRRjkno1vFg2a2QIc6oy4w_Z7KcOZZEQXhyOw31GKg",range = "A1",sheet = "RESULTADO GERAL GRUPOS")



#VERIFICA IDs REPETIDOS

RESULT_TRANSITIONS_FEV_MAR_23 %>% .[duplicated(.$ID_PEDIDO),]


# JOIN CPF

PARTICIPANTES_CAMPANHAS_LOJAS_FEV_MAR_23 <-
  
left_join(RESULT_TRANSITIONS_FEV_MAR_23_LOJAS,
  
PARTICIPANTES_CAMPANHA %>% rename(CLICODIGO=2) %>% .[,c(2,3,4)], by="CLICODIGO" )



# JOIN CPF

PARTICIPANTES_CAMPANHAS_GRUPOS_FEV_MAR_23 <-

left_join(RESULT_TRANSITIONS_FEV_MAR_23_GRUPOS,
          
          PARTICIPANTES_CAMPANHA %>% rename(CLICODIGO=2) %>% .[,c(2,3,4)], by="CLICODIGO" )



range_write(PARTICIPANTES_CAMPANHAS_LOJAS_FEV_MAR_23,ss="1ZQRRjkno1vFg2a2QIc6oy4w_Z7KcOZZEQXhyOw31GKg",range = "A1",sheet = "PARTICIPANTES CAMPANHAS LOJAS")

range_write(PARTICIPANTES_CAMPANHAS_GRUPOS_FEV_MAR_23 ,ss="1ZQRRjkno1vFg2a2QIc6oy4w_Z7KcOZZEQXhyOw31GKg",range = "A1",sheet = "PARTICIPANTES CAMPANHAS GRUPOS")


