## CAMPANHA TRANSITIONS PONTOS ESSILOR OUT DEZ 2022

library(DBI)
library(tidyverse)
library(lubridate)
library(googlesheets4)
library(glue)

## ============================================================================================

con2 <- dbConnect(odbc::odbc(), "reproreplica")

## =============================================================================================================         
### CLIENTES TRANSITIONS


CLIENTES_TGEN8_10_12_22 <- read_sheet(ss="1sLMXlqmYrBWEfqhxzC6gDgLc8T-vaBxZLEVZy3n8QZA",sheet = "CAMPANHA2")

cli <- dbGetQuery(con2,"SELECT DISTINCT C.CLICODIGO,
                          CLINOMEFANT,
                           CLICNPJCPF,
                                    SETOR
                                     FROM CLIEN C
                                      LEFT JOIN (SELECT CLICODIGO,E.ZOCODIGO,CIDNOME,ZODESCRICAO SETOR,ENDCODIGO FROM ENDCLI E
                                       LEFT JOIN CIDADE CID ON E.CIDCODIGO=CID.CIDCODIGO
                                        LEFT JOIN (SELECT ZOCODIGO,ZODESCRICAO FROM ZONA WHERE ZOCODIGO IN (20,21,22,23,24,25,28))Z ON E.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
                                         LEFT JOIN GRUPOCLI GR ON C.GCLCODIGO=GR.GCLCODIGO
                                          WHERE CLICLIENTE='S'")


CLIENTES_TGEN8_10_12_22_3 <- left_join(CLIENTES_TGEN8_10_12_22 %>% 
                                     select(CLICODIGO),cli %>% select(CLICODIGO,CLINOMEFANT,SETOR),by="CLICODIGO") 



CP_TRANSITIONS_10_12_22_sql <- glue_sql("
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON 
       C.CLICODIGO=A.CLICODIGO WHERE C.CLICODIGO IN ({CLIENTES_TGEN8_10_12_22_3$CLICODIGO*}) ),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,SETOR,CLINOMEFANT,PEDAUTORIZOU  
FROM PEDID 
INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
WHERE PEDDTBAIXA
BETWEEN '01.10.2022'
       AND '31.12.2022'
AND PEDSITPED <>'C'),

-- Varilux Series Transitions 100 pontos

PROD1 AS (SELECT PROCODIGO,
        PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND 
         (PRODESCRICAO LIKE '%VARILUX X%' AND 
           PRODESCRICAO LIKE '%TGEN8%') OR 
           (PRODESCRICAO LIKE '%VARILUX E%' AND 
             PRODESCRICAO LIKE '%TGEN8%') ),

-- Varilux Digital Transitions 70 pontos

PROD2 AS (SELECT PROCODIGO,
        PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND 
         ((PRODESCRICAO LIKE '%COMFORT MAX%' AND
            PRODESCRICAO LIKE '%TGEN8%') OR 
             (PRODESCRICAO LIKE '%LIBERTY%' AND 
               PRODESCRICAO LIKE '%TGEN8%') OR 
               (PRODESCRICAO LIKE '%PHYSIO%' AND 
                 PRODESCRICAO LIKE '%TGEN8%')) AND
                  GR1CODIGO=15 AND PROSITUACAO='A'AND 
                   PROCODIGO2 IS NULL),
                   
-- Varilux tradicional Transitions 60 pontos

PROD3 AS (SELECT PROCODIGO,
        PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND 
         ((PRODESCRICAO LIKE '%COMFORT%' AND 
           PRODESCRICAO LIKE '%TGEN8%') OR 
           (PRODESCRICAO LIKE '%LIBERTY%' AND 
             PRODESCRICAO LIKE '%TGEN8%') OR 
               (PRODESCRICAO LIKE '%PHYSIO%' AND 
                 PRODESCRICAO LIKE '%TGEN8%')) AND
                  LEFT(PROCODIGO,2)='LP' AND 
                   PROSITUACAO='A'AND 
                    PROCODIGO2 IS NULL),

-- Progressivo Kodak transitions 50 pontos

PROD4 AS (SELECT PROCODIGO,
        PRODESCRICAO FROM PRODU WHERE MARCODIGO=24 AND 
         PRODESCRICAO LIKE '%TGEN8%' AND 
          LEFT(PROCODIGO,2) IN ('LD','LP') AND 
            PROSITUACAO='A'AND 
             PROCODIGO2 IS NULL),
             
-- lente visão simples transitions kodak single eyezen 50 pontos             

PROD5 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE  
             (PRODESCRICAO LIKE '%TGEN8%') AND 
               (PRODESCRICAO LIKE '%EYEZEN%' OR 
                PRODESCRICAO LIKE '%KODAK SINGLE%')AND
                 (PRODESCRICAO NOT LIKE '%SCL%') AND 
                   GR2CODIGO=3 AND GR1CODIGO<>1 AND 
                    PROSITUACAO='A'AND 
                     PROCODIGO2 IS NULL),

-- lente pronta crizal transitions 35 pontos

PROD6 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE  
             (PRODESCRICAO LIKE '%TGEN8%' AND 
               PRODESCRICAO LIKE '%CRIZAL%') AND 
                GR2CODIGO=3 AND 
                 PROSITUACAO='A'AND 
                   PROCODIGO2=IIF(PROCODIGO2 IS NULL,PROCODIGO,PROCODIGO2)),

-- lente pronta kodak no reflex transitions 25 pontos

PROD7 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE  
             (PRODESCRICAO LIKE '%TGEN8%' AND 
               PRODESCRICAO LIKE '%NO REFLEX%') AND 
                GR2CODIGO=3 AND PROSITUACAO='A'AND 
                  PROCODIGO2=IIF(PROCODIGO2 IS NULL,PROCODIGO,PROCODIGO2)),


PED_PROMO_PAP AS (SELECT P.ID_PEDIDO ID_PEDIDO_PROMO FROM PDPRD P
 INNER JOIN PD ON P.ID_PEDIDO=PD.ID_PEDIDO
   WHERE PROCODIGO='PAP'),
   
   
PED_PROMO_PLUGIN AS (SELECT ID_PEDIDPROMOCAO ID_PEDIDO_PROMO FROM PEDIDPROMO P
   INNER JOIN PD ON P.ID_PEDIDPROMOCAO=PD.ID_PEDIDO),

PED_PROMO_UNION AS (SELECT ID_PEDIDO_PROMO FROM PED_PROMO_PAP UNION
SELECT ID_PEDIDO_PROMO FROM PED_PROMO_PLUGIN)

--- PROD1

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD1.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(100 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD1 ON PDPRD.PROCODIGO=PROD1.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD2

SELECT
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD2.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(70 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD2 ON PDPRD.PROCODIGO=PROD2.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD3

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PROD3.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(60 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD3 ON PDPRD.PROCODIGO=PROD3.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD4

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD4.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(50 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD4 ON PDPRD.PROCODIGO=PROD4.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD5

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD5.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(50 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD5 ON PDPRD.PROCODIGO=PROD5.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD6

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD6.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(35 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD6 ON PDPRD.PROCODIGO=PROD6.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

--- PROD7

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD7.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(25 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD7 ON PDPRD.PROCODIGO=PROD7.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2


 ")

CP_TRANSITIONS_10_12_22<-  dbGetQuery(con2,CP_TRANSITIONS_10_12_22_sql) 


View(CP_TRANSITIONS_10_12_22)

CP_TRANSITIONS_10_12_22 %>% summarize(v=sum(VRVENDA))

CP_TRANSITIONS_10_12_22 %>% summarize(v=sum(BONUS))





OBS_CP_TRANSITIONS_10_12_22 <- paste0("TRANSITIONS PONTOS ESSILOR OUT DEZ 22") 


## JOIN CPF

LIST_CP_TRANSITIONS_10_12_22   <- inner_join(CP_TRANSITIONS_10_12_22 ,BASE_CPF,by="CLICODIGO") %>% 
  mutate(OBS=OBS_CP_TRANSITIONS_10_12_22 )

View(LIST_CP_TRANSITIONS_10_12_22 )


### PAY

PAG_CP_TRANSITIONS_10_12_22 <- LIST_CP_TRANSITIONS_10_12_22  %>% group_by(CPF) %>% 
  summarize(BONUS=round(sum(BONUS),2)) %>% 
  mutate(OBS=OBS_CP_TRANSITIONS_10_12_22 ) 



## RESULTADO 


X1 <- CP_TRANSITIONS_10_12_22 %>% group_by(CLICODIGO) %>% summarize(BONUS=sum(BONUS))

CP_TRANSITIONS_10_12_22 %>% .[duplicated(.$ID_PEDIDO),]


RS_TRANSITIONS_10_12_22 <- left_join(X1,CLIENTES_TGEN8_10_12_22_3,by="CLICODIGO") %>% arrange(desc(BONUS))


write_sheet(RS_TRANSITIONS_10_12_22,ss="1955p2k0BD-_nq6aINotdhxheIm7q2df0HBIteB67ZDo",sheet = "RESUMO")

write_sheet(CP_TRANSITIONS_10_12_22,ss="1955p2k0BD-_nq6aINotdhxheIm7q2df0HBIteB67ZDo",sheet = "PEDIDOS")

write_sheet(RESULT_CAMPANHA_TRANSITIONS_P,ss="1955p2k0BD-_nq6aINotdhxheIm7q2df0HBIteB67ZDo",sheet = "PARTICIPANTES")


## PARTICIPANTES =========================================================================





PARTICIPANTES_CAMPANHA <- read_sheet("",
                                     sheet = 'DADOS') %>% rename(CLICODIGO=`CÓDIGO DA ÓTICA`) %>% 
  mutate(CLICODIGO=as.numeric(CLICODIGO))


participantes_transitions <- left_join(RS_TRANSITIONS_10_12_22,PARTICIPANTES_CAMPANHA, by="CLICODIGO") %>% filter(BONUS>=150)

write_sheet(participantes_transitions ,ss="",sheet = "PARTICIPANTES3")



## EMISSAO =========================================================================


CAMPANHA_TRANS_ESSILOR_EMISS_CARTOES <-left_join(participantes_transitions %>%   
                                                   mutate(CPF=as.character(CPF)),CARTOES_1022,by="CPF") %>% 
  filter(is.na(`Número do Série`)) %>% 
  filter(CPF!='NULL') %>% 
  filter(CLICODIGO!=397) %>% 
  .[c(-3,-7,-15),] %>% 
  mutate(OBS='CAMPANHA TRANSITIONS ESSILOR 08_0922') %>%
  .[,c(7,2,19,5,1,6,8,9)] 
View(CAMPANHA_TRANS_ESSILOR_EMISS_CARTOES )


range_write("",data = CAMPANHA_TRANS_ESSILOR_EMISS_CARTOES,range = "A7",col_names = FALSE)



## STATUS PAGAMENTOS =========================================================================



STATUS_PAG_TRANS <-left_join(RS_TRANSITIONS_0922,BASE_CPF,by="CLICODIGO") 


PAG_ALELO <- left_join(ALELO_10_12_22 %>% rename(NSERIE=4),CARTOES_10_12_22 %>% rename(NSERIE=5),by="NSERIE") 

View(PAG_ALELO)

left_join(STATUS_PAG_TRANS %>% mutate(CPF=as.character(CPF)),
          PAG_ALELO %>% mutate(CPF=as.character(CPF)),by="CPF") %>% View()


range_write("",
            sheet = "PAGAMENTOS" ,
            data = STATUS_PAG_TRANS ,
            range = "A1") 


## STATUS 2 =========================================================================


read_sheet("",
           sheet = 'PAGAMENTOS')  %>% 
  filter(is.na(STATUS)) %>% 
  left_join(.,PARTICIPANTES_CAMPANHA,by="CLICODIGO") %>% View()







